//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// HospitalSystem.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HOSPITALSYSTEM_DIALOG       102
#define IDD_AlreadyPatient              103
#define IDD_DoctorPage1                 104
#define IDD_DetailPage                  105
#define IDD_SearchPage                  106
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SignUP               130
#define IDD_DIALOG_Doctor               132
#define IDD_DIALOG_HospitamOffice       132
#define IDD_DIALOG_AddPatient           136
#define IDD_DIALOG_Add_Appointment      138
#define IDR_MENU1                       141
#define IDD_DIALOG1_Payment             144
#define IDB_BITMAP3                     152
#define IDB_BITMAP1                     159
#define IDB_BITMAP2                     160
#define IDB_BITMAP4                     162
#define IDB_BITMAP5                     163
#define IDB_BITMAP6                     164
#define IDB_BITMAP7                     165
#define ID_Button_login                 1000
#define IDC_EDIT_INput_Id               1001
#define IDC_EDIT_INput_PW               1002
#define IDC_EDIT_SIgnUp_ID              1003
#define IDC_EDIT_SignUp_pw              1004
#define IDC_EDIT_SignUp_Name            1005
#define IDC_Register                    1006
#define IDC_BUTTON_CheckID              1007
#define IDC_EDIT_SignUp_Phone           1008
#define IDC_EDIT_SignUp_Employee        1009
#define IDC_LIST1                       1010
#define IDC_LIST_RECORDS                1011
#define IDC_BUTTON_AddPatient           1012
#define IDC_BUTTON_addAppointment       1013
#define IDC_EDIT_Name                   1014
#define IDC_EDIT_Phone                  1015
#define IDC_EDIT_DoctorId               1016
#define IDC_EDIT_symptoms               1017
#define IDC_EDIT_Date                   1018
#define IDC_BUTTON_Appointment          1019
#define IDC_EDIT_PatientName            1020
#define IDC_EDIT_Patient_Phon           1021
#define IDC_EDIT_PatientAddr            1022
#define IDC_EDIT_PatientBirth           1023
#define IDC_BUTTON_ADD                  1024
#define IDC_BTN_1                       1025
#define IDC_MONTHCALENDAR1              1026
#define IDC_LIST3                       1028
#define IDC_BUTTON2                     1029
#define IDC_LIST_wait                   1030
#define IDC_BUTTON3                     1031
#define IDC_LIST5                       1032
#define IDC_BUTTON4                     1033
#define IDC_EDIT_SignUp_license_id      1035
#define IDC_EDIT_SignUp_department      1036
#define IDC_EDIT_SignUp_departmentCode  1037
#define IDC_EDIT_SignUP_specialty       1038
#define IDC_EDIT_ResidentNumber         1039
#define IDC_CHECK1_MAN                  1041
#define IDC_CHECK_WOMAN                 1042
#define IDC_EDIT_dosing_list            1043
#define IDC_EDIT_blood_type             1044
#define IDC_EDIT_emergencyNumber        1045
#define IDC_STATIC_ID                   1047
#define IDC_MONTHCALENDAR_Appointment   1049
#define IDC_COMBO1                      1050
#define IDC_BTN_alreadyPatient          1051
#define IDC_BUTTON1                     1052
#define IDC_LIST_PatientInformation     1054
#define IDC_LIST_MedicineHistroy        1055
#define IDC_LIST_ChartHistory           1057
#define IDC_BUTTON5                     1058
#define IDC_BUTTON6                     1059
#define IDC_EDIT_Method                 1063
#define IDC_EDIT_dosage                 1065
#define IDC_BUTTON7                     1066
#define IDC_EDIT_Name1                  1067
#define IDC_EDIT_CC                     1069
#define IDC_EDIT_DCode                  1070
#define IDC_EDIT_Diagnoisis             1071
#define IDC_EDIT_Menifestitation        1072
#define IDC_BUTTON8                     1073
#define IDC_LIST_MCode                  1074
#define IDC_EDIT1_Mcode                 1075
#define IDC_EDIT_Mcode                  1075
#define IDC_BUTTON_OKM                  1076
#define IDC_BUTTON10                    1077
#define IDC_BUTTON_OKD                  1077
#define IDC_LIST_DCode                  1078
#define IDC_EDIT_ResidentNumber1        1079
#define IDC_LIST_appointment            1080
#define IDC_EDIT1                       1081
#define IDC_EDIT_daily_dosage           1081
#define IDC_EDIT_detaiName              1081
#define IDC_EDIT_srn                    1081
#define IDC_EDIT_SSN                    1081
#define IDC_EDIT_S                      1081
#define IDC_EDIT_                       1081
#define IDC_EDIT2                       1082
#define IDC_EDIT_frequency              1082
#define IDC_EDIT_detailResidentNumber   1082
#define IDC_EDIT3                       1083
#define IDC_EDIT_duration               1083
#define IDC_EDIT_detailGender           1083
#define IDC_EDIT4                       1084
#define IDC_EDIT_note                   1084
#define IDC_EDIT_detailAddr             1084
#define IDC_MONTHCALENDAR_doctorPage    1085
#define IDC_EDIT_detailPhone            1086
#define IDC_EDIT_SearchName             1086
#define IDC_EDIT_detailEmer             1087
#define IDC_EDIT_searchPhone            1087
#define IDC_EDIT_detailDosing           1088
#define IDC_EDIT_searchlEmer            1088
#define IDC_EDIT_detailBloody           1089
#define IDC_EDIT_searchDosing           1089
#define IDC_BUTTON_SearchPatient        1090
#define IDC_EDIT_searchBloody           1090
#define IDC_BUTTON_Search               1091
#define IDC_EDIT_searchlResidentNumber  1092
#define IDC_EDIT_searchGender           1093
#define IDC_EDIT_searchAddr             1094
#define IDC_SCROLLBAR1                  1095
#define IDC_BUTTON9                     1096
#define IDC_LIST2                       1097
#define IDC_STATIC_PATIENT_LABEL_ADDRESS 1097
#define IDC_STATIC_RESULT               1098
#define IDC_BUTTON_MARK_PAID            1099
#define IDC_LIST_PRESCRIPTIONS          1100
#define IDC_BUTTON_PRINT_RECEIPT        1101
#define IDC_STATIC_PATIENT_LABEL_NAME3  1103
#define IDC_STATIC_PATIENT_LABEL_GENDER 1104
#define IDC_STATIC_PATIENT_LABEL_BLOOD  1105
#define IDC_STATIC_PATIENT_LABEL_NAME6  1106
#define IDC_STATIC_PATIENT_LABEL_PHONE  1107
#define IDC_STATIC_PATIENT_LABEL_EMERGENCY 1108
#define IDC_STATIC_PATIENT_LABEL_NAME   1109
#define IDC_STATIC_PATIENT_NAME         1110
#define IDC_STATIC_PATIENT_ADDRESS      1111
#define IDC_STATIC_PAYMENT_DATE         1112
#define IDC_STATIC_PATIENT_GENDER       1113
#define IDC_STATIC_PATIENT_BLOOD        1114
#define IDC_STATIC_PAYMENT_PDATE        1115
#define IDC_STATIC_PATIENT_PHONE        1116
#define IDC_STATIC_PATIENT_EMERGENCY    1117
#define IDC_STATIC_MEMO                 1118
#define IDC_doc_text1                   1119
#define IDC_doc_text2                   1120
#define IDC_doc_text3                   1121
#define IDC_doc_text4                   1122
#define IDC_doc_text5                   1123
#define IDC_doc_text6                   1124
#define IDC_doc_text7                   1125
#define IDC_doc_text8                   1126
#define IDC_doc_text9                   1127
#define IDC_doc_text10                  1128
#define IDC_picPatient                  1129
#define IDC_BTN_Clear                   1130
#define IDC_BTN_Clear2                  1131
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1132
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
